name: Build extension on release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: "Set up Node.js"
        uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2
        with:
          node-version: "20"

      - name: "Install dependencies"
        run: yarn install --frozen-lockfile

      - name: "Build extension"
        run: yarn run package

      - name: upload vsix
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./labs-ai-tools-vscode-${{ github.event.release.tag_name }}.vsix
          asset_name: labs-ai-tools-vscode-${{ github.event.release.tag_name }}.vsix
          asset_content_type: application/octet-stream
