name: Run tests on extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: "Install dependencies"
        run: yarn install
      - name: "Run tests"
        run: xvfb-run -a yarn test
